### ISSUE TITLE
need simple documentation

### ISSUE THREAD

**Issue by guneysus** [AhmetHuseyinDOK/AtikJS#1]
I skimmed the source code and looks good to me.

Can you provide a simple readme/doc from installing to deployement for trying, evaluating and giving feedback to you about Atik. Me or someone may use the Atik for side projects.

:+1:

**Comment by AhmetHuseyinDOK** [comment]
I didn’t have time to write a readme because now I am rewriting the core and render methods for a better html rendering, data management. And I am trying to provide a mechanism to mount and unmount callback methods for components. 

Yet AtikJS is easy to use. Check this link out: [Word Recorder](https://ahmethuseyindok.github.io/AtikJS/word_recorder/)

This application was built using AtikJS and source code is also available [here](https://github.com/AhmetHuseyinDOK/AtikJS/blob/master/word_recorder/index.js)

**Comment by AhmetHuseyinDOK** [comment]
@guneysus Well, it's been a while 😅 but I added a simple documentation. You can check it out and give it a try
